interface IStablePhantomPool {
  function DOMAIN_SEPARATOR (  ) external view returns ( bytes32 );
  function allowance ( address owner, address spender ) external view returns ( uint256 );
  function approve ( address spender, uint256 amount ) external returns ( bool );
  function balanceOf ( address account ) external view returns ( uint256 );
  function decimals (  ) external view returns ( uint8 );
  function decreaseAllowance ( address spender, uint256 amount ) external returns ( bool );
  function getActionId ( bytes4 selector ) external view returns ( bytes32 );
  function getAmplificationParameter (  ) external view returns ( uint256 value, bool isUpdating, uint256 precision );
  function getAuthorizer (  ) external view returns ( address );
  function getBptIndex (  ) external view returns ( uint256 );
  function getCachedProtocolSwapFeePercentage (  ) external view returns ( uint256 );
  function getDueProtocolFeeBptAmount (  ) external view returns ( uint256 );
  function getLastInvariant (  ) external view returns ( uint256 lastInvariant, uint256 lastInvariantAmp );
  function getMinimumBpt (  ) external pure returns ( uint256 );
  function getOwner (  ) external view returns ( address );
  function getPausedState (  ) external view returns ( bool paused, uint256 pauseWindowEndTime, uint256 bufferPeriodEndTime );
  function getPoolId (  ) external view returns ( bytes32 );
  function getRate (  ) external view returns ( uint256 );
  function getRateProviders (  ) external view returns ( address[] memory providers );
  function getScalingFactor ( address token ) external view returns ( uint256 );
  function getScalingFactors (  ) external view returns ( uint256[] memory );
  function getSwapFeePercentage (  ) external view returns ( uint256 );
  function getTokenRate ( address token ) external view returns ( uint256 );
  function getTokenRateCache ( address token ) external view returns ( uint256 rate, uint256 duration, uint256 expires );
  function getVault (  ) external view returns ( address );
  function getVirtualSupply (  ) external view returns ( uint256 );
  function increaseAllowance ( address spender, uint256 addedValue ) external returns ( bool );
  function name (  ) external view returns ( string memory );
  function nonces ( address owner ) external view returns ( uint256 );
  function onExitPool ( bytes32 poolId, address sender, address recipient, uint256[] memory  balances, uint256 lastChangeBlock, uint256 protocolSwapFeePercentage, bytes memory  userData ) external returns ( uint256[] memory , uint256[] memory  );
  function onJoinPool ( bytes32 poolId, address sender, address recipient, uint256[] memory  balances, uint256 lastChangeBlock, uint256 protocolSwapFeePercentage, bytes memory  userData ) external returns ( uint256[] memory , uint256[] memory );
  function permit ( address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s ) external;
  function queryExit ( bytes32 poolId, address sender, address recipient, uint256[] memory  balances, uint256 lastChangeBlock, uint256 protocolSwapFeePercentage, bytes memory  userData ) external returns ( uint256 bptIn, uint256[] memory  amountsOut );
  function queryJoin ( bytes32 poolId, address sender, address recipient, uint256[] memory  balances, uint256 lastChangeBlock, uint256 protocolSwapFeePercentage, bytes memory  userData ) external returns ( uint256 bptOut, uint256[] memory  amountsIn );
  function setAssetManagerPoolConfig ( address token, bytes memory poolConfig ) external;
  function setPaused ( bool paused ) external;
  function setSwapFeePercentage ( uint256 swapFeePercentage ) external;
  function setTokenRateCacheDuration ( address token, uint256 duration ) external;
  function startAmplificationParameterUpdate ( uint256 rawEndValue, uint256 endTime ) external;
  function stopAmplificationParameterUpdate (  ) external;
  function symbol (  ) external view returns ( string memory );
  function totalSupply (  ) external view returns ( uint256 );
  function transfer ( address recipient, uint256 amount ) external returns ( bool );
  function transferFrom ( address sender, address recipient, uint256 amount ) external returns ( bool );
  function updateCachedProtocolSwapFeePercentage (  ) external;
  function updateTokenRateCache ( address token ) external;
}